services:
  api:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      - DATABASE_USER=rm99853
      - DATABASE_PWD=281290