CREATE SEQUENCE SEQ_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_USUARIOS(
    ID INTEGER DEFAULT SEQ_USUARIO.NEXTVAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(100) NOT NULL
);

ALTER TABLE TBL_USUARIOS ADD CONSTRAINT USUARIO_PK PRIMARY KEY (ID);