CREATE SEQUENCE SEQ_CASA
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_CASAS(
    ID INTEGER DEFAULT SEQ_CASA.NEXTVAL NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    CEP VARCHAR(10) NOT NULL
);

ALTER TABLE TBL_CASAS ADD CONSTRAINT CASA_PK PRIMARY KEY (ID);