CREATE SEQUENCE SEQ_DISPOSITIVO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_DISPOSITIVOS_SEGURANCA(
    ID INTEGER DEFAULT SEQ_DISPOSITIVO.NEXTVAL NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    LOCAL_INSTALACAO VARCHAR(100) NOT NULL,
    ID_CASA INTEGER NOT NULL
);

ALTER TABLE TBL_DISPOSITIVOS_SEGURANCA ADD CONSTRAINT DISPOSITIVO_PK PRIMARY KEY (ID);

ALTER TABLE TBL_DISPOSITIVOS_SEGURANCA ADD CONSTRAINT FK_DISPOSITVO_CASA_ID_CASA_ID FOREIGN KEY (ID_CASA) REFERENCES TBL_CASAS(id);

