CREATE SEQUENCE SEQ_NOTIFICACAO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_NOTIFICACOES(
    ID INTEGER DEFAULT SEQ_NOTIFICACAO.NEXTVAL NOT NULL,
    ID_DISPOSITIVO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    DATA DATE DEFAULT SYSDATE NOT NULL,
    TIPO VARCHAR2(20),
    DESCRICAO VARCHAR2(200),
    STATUS VARCHAR2(20)
);
ALTER TABLE TBL_NOTIFICACOES ADD CONSTRAINT NOTIFICACAO_PK PRIMARY KEY (ID);
ALTER TABLE TBL_NOTIFICACOES ADD CONSTRAINT fk_notificacoes_id_dispositivo FOREIGN KEY (id_dispositivo) REFERENCES TBL_DISPOSITIVOS_SEGURANCA(id);
ALTER TABLE TBL_NOTIFICACOES ADD CONSTRAINT fk_notificacoes_id_usuario FOREIGN KEY (id_usuario) REFERENCES TBL_USUARIOS(id);



